// Añade traducciones de nombres de rutas curadas a los 8 locales bajo curatedRoutes.routes.<id>.name
const fs = require('fs');
const path = require('path');

const DIR = 'C:\\Users\\usuario\\Desktop\\MonumentosFront\\src\\i18n\\locales';

// Para cada ruta: traducciones { es, ca, en, fr, it, pt, gl, eu }
const ROUTES = {
  'romanico-camino-frances': {
    es: 'Camino Francés – Ruta Románica',
    ca: 'Camí Francès – Ruta Romànica',
    en: 'French Way – Romanesque Route',
    fr: 'Camino Francés – Route romane',
    it: 'Camino Francés – Via Romanica',
    pt: 'Caminho Francês – Rota Românica',
    gl: 'Camiño Francés – Ruta Románica',
    eu: 'Bide Frantsesa – Ibilbide Erromanikoa',
  },
  'romanico-valle-boi': {
    es: 'Valle de Boí – Románico Lombardo UNESCO',
    ca: 'Vall de Boí – Romànic Llombard UNESCO',
    en: 'Vall de Boí – Lombard Romanesque UNESCO',
    fr: 'Vall de Boí – Roman lombard UNESCO',
    it: 'Vall de Boí – Romanico lombardo UNESCO',
    pt: 'Vall de Boí – Românico Lombardo UNESCO',
    gl: 'Val de Boí – Románico Lombardo UNESCO',
    eu: 'Boí Harana – Erromaniko Lombardiarra UNESCO',
  },
  'romanico-palentino': {
    es: 'Románico Palentino',
    ca: 'Romànic Palentí',
    en: 'Palentine Romanesque',
    fr: 'Roman de Palencia',
    it: 'Romanico di Palencia',
    pt: 'Românico de Palencia',
    gl: 'Románico Palentino',
    eu: 'Palentziako Erromanikoa',
  },
  'romanico-aragones': {
    es: 'Románico Aragonés – Jacetania y Serrablo',
    ca: 'Romànic Aragonès – Jacetània i Serrablo',
    en: 'Aragonese Romanesque – Jacetania and Serrablo',
    fr: 'Roman aragonais – Jacetania et Serrablo',
    it: 'Romanico aragonese – Jacetania e Serrablo',
    pt: 'Românico Aragonês – Jacetania e Serrablo',
    gl: 'Románico Aragonés – Jacetania e Serrablo',
    eu: 'Aragoiko Erromanikoa – Jacetania eta Serrablo',
  },
  'romanico-cantabrico': {
    es: 'Románico Cantábrico – Camino del Norte',
    ca: 'Romànic Cantàbric – Camí del Nord',
    en: 'Cantabrian Romanesque – Northern Way',
    fr: 'Roman cantabrique – Chemin du Nord',
    it: 'Romanico cantabrico – Cammino del Nord',
    pt: 'Românico Cantábrico – Caminho do Norte',
    gl: 'Románico Cantábrico – Camiño do Norte',
    eu: 'Kantauriko Erromanikoa – Iparraldeko Bidea',
  },
  'romanico-soriano': {
    es: 'Románico Soriano',
    ca: 'Romànic de Sòria',
    en: 'Soria Romanesque',
    fr: 'Roman de Soria',
    it: 'Romanico di Soria',
    pt: 'Românico de Sória',
    gl: 'Románico de Soria',
    eu: 'Soriako Erromanikoa',
  },
  'gotico-catedrales-francia': {
    es: 'Grandes Catedrales Góticas de Francia',
    ca: 'Grans Catedrals Gòtiques de França',
    en: 'Great Gothic Cathedrals of France',
    fr: 'Grandes cathédrales gothiques de France',
    it: 'Grandi cattedrali gotiche di Francia',
    pt: 'Grandes Catedrais Góticas de França',
    gl: 'Grandes Catedrais Góticas de Francia',
    eu: 'Frantziako Katedral Gotiko Handiak',
  },
  'gotico-levantino': {
    es: 'Gótico Levantino – Valencia',
    ca: 'Gòtic Llevantí – València',
    en: 'Levantine Gothic – Valencia',
    fr: 'Gothique levantin – Valence',
    it: 'Gotico levantino – Valencia',
    pt: 'Gótico Levantino – Valência',
    gl: 'Gótico Levantino – Valencia',
    eu: 'Levantear Gotikoa – Valentzia',
  },
  'gotico-catedrales-castilla': {
    es: 'Tres Catedrales Góticas de Castilla',
    ca: 'Tres Catedrals Gòtiques de Castella',
    en: 'Three Gothic Cathedrals of Castile',
    fr: 'Trois cathédrales gothiques de Castille',
    it: 'Tre cattedrali gotiche di Castiglia',
    pt: 'Três Catedrais Góticas de Castela',
    gl: 'Tres Catedrais Góticas de Castela',
    eu: 'Gaztelako Hiru Katedral Gotikoak',
  },
  'mudejar-aragones': {
    es: 'Mudéjar Aragonés – Patrimonio UNESCO',
    ca: 'Mudèjar Aragonès – Patrimoni UNESCO',
    en: 'Aragonese Mudejar – UNESCO Heritage',
    fr: 'Mudéjar aragonais – Patrimoine UNESCO',
    it: 'Mudéjar aragonese – Patrimonio UNESCO',
    pt: 'Mudéjar Aragonês – Património UNESCO',
    gl: 'Mudéxar Aragonés – Patrimonio UNESCO',
    eu: 'Aragoiko Mudejarra – UNESCO Ondarea',
  },
  'renacimiento-ubeda-baeza': {
    es: 'Renacimiento Andaluz – Úbeda y Baeza UNESCO',
    ca: 'Renaixement Andalús – Úbeda i Baeza UNESCO',
    en: 'Andalusian Renaissance – Úbeda and Baeza UNESCO',
    fr: 'Renaissance andalouse – Úbeda et Baeza UNESCO',
    it: 'Rinascimento andaluso – Úbeda e Baeza UNESCO',
    pt: 'Renascimento Andaluz – Úbeda e Baeza UNESCO',
    gl: 'Renacemento Andaluz – Úbeda e Baeza UNESCO',
    eu: 'Andaluziako Errenazimentua – Úbeda eta Baeza UNESCO',
  },
  'barroco-salamanca': {
    es: 'Barroco Churrigueresco – Salamanca',
    ca: 'Barroc Xurrigueresc – Salamanca',
    en: 'Churrigueresque Baroque – Salamanca',
    fr: 'Baroque churrigueresque – Salamanque',
    it: 'Barocco churrigueresco – Salamanca',
    pt: 'Barroco Churrigueresco – Salamanca',
    gl: 'Barroco Churrigueresco – Salamanca',
    eu: 'Barroko Txurriguereskoa – Salamanca',
  },
  'cister-cataluna': {
    es: 'Ruta del Cister – Cataluña',
    ca: 'Ruta del Cister – Catalunya',
    en: 'Cistercian Route – Catalonia',
    fr: 'Route cistercienne – Catalogne',
    it: 'Itinerario cistercense – Catalogna',
    pt: 'Rota Cisterciense – Catalunha',
    gl: 'Ruta do Cister – Cataluña',
    eu: 'Zisterzieren Ibilbidea – Katalunia',
  },
  'mosteiros-portugal': {
    es: 'Ruta de los Monasterios – Portugal UNESCO',
    ca: 'Ruta dels Monestirs – Portugal UNESCO',
    en: 'Monasteries Route – Portugal UNESCO',
    fr: 'Route des monastères – Portugal UNESCO',
    it: 'Itinerario dei monasteri – Portogallo UNESCO',
    pt: 'Rota dos Mosteiros – Portugal UNESCO',
    gl: 'Ruta dos Mosteiros – Portugal UNESCO',
    eu: 'Monasterioen Ibilbidea – Portugal UNESCO',
  },
  'abadias-normandia': {
    es: 'Abadías de Normandía',
    ca: 'Abadies de Normandia',
    en: 'Abbeys of Normandy',
    fr: 'Abbayes de Normandie',
    it: 'Abbazie di Normandia',
    pt: 'Abadias da Normandia',
    gl: 'Abadías de Normandía',
    eu: 'Normandiako Abadiak',
  },
  'chateaux-loire': {
    es: 'Châteaux del Valle del Loira',
    ca: 'Châteaux de la Vall del Loira',
    en: 'Châteaux of the Loire Valley',
    fr: 'Châteaux de la Loire',
    it: 'Castelli della Valle della Loira',
    pt: 'Châteaux do Vale do Loire',
    gl: 'Châteaux do Val do Loira',
    eu: 'Loira Haraneko Châteaux',
  },
  'castillos-cataros': {
    es: 'Castillos Cátaros – Languedoc',
    ca: 'Castells Càtars – Llenguadoc',
    en: 'Cathar Castles – Languedoc',
    fr: 'Châteaux cathares – Languedoc',
    it: 'Castelli catari – Linguadoca',
    pt: 'Castelos Cátaros – Languedoque',
    gl: 'Castelos Cátaros – Languedoc',
    eu: 'Katarren Gazteluak – Langedoc',
  },
  'castillos-castilla': {
    es: 'Castillos de Castilla – Frontera y Defensa',
    ca: 'Castells de Castella – Frontera i Defensa',
    en: 'Castles of Castile – Frontier and Defense',
    fr: 'Châteaux de Castille – Frontière et défense',
    it: 'Castelli di Castiglia – Frontiera e difesa',
    pt: 'Castelos de Castela – Fronteira e Defesa',
    gl: 'Castelos de Castela – Fronteira e Defensa',
    eu: 'Gaztelako Gazteluak – Muga eta Defentsa',
  },
  'ruta-templaria': {
    es: 'Ruta Templaria – España y Portugal',
    ca: 'Ruta Templera – Espanya i Portugal',
    en: 'Templar Route – Spain and Portugal',
    fr: 'Route templière – Espagne et Portugal',
    it: 'Itinerario templare – Spagna e Portogallo',
    pt: 'Rota Templária – Espanha e Portugal',
    gl: 'Ruta Templaria – España e Portugal',
    eu: 'Tenplarioen Ibilbidea – Espainia eta Portugal',
  },
  'ruta-nazari': {
    es: 'Ruta Nazarí – Legado Andalusí',
    ca: 'Ruta Nassarí – Llegat Andalusí',
    en: 'Nasrid Route – Andalusi Legacy',
    fr: 'Route nasride – Héritage andalou',
    it: 'Itinerario nasride – Eredità andalusa',
    pt: 'Rota Nasrida – Legado Andaluz',
    gl: 'Ruta Nazarí – Legado Andalusí',
    eu: 'Nasriden Ibilbidea – Al-Andalusko Ondarea',
  },
  'reinos-taifa': {
    es: 'Reinos Taifa – Palacios y Alcazabas',
    ca: 'Regnes Taifa – Palaus i Alcassabes',
    en: 'Taifa Kingdoms – Palaces and Alcazabas',
    fr: 'Royaumes de Taïfa – Palais et alcazabas',
    it: 'Regni di Taifa – Palazzi e alcazabe',
    pt: 'Reinos Taifa – Palácios e Alcáçovas',
    gl: 'Reinos Taifa – Pazos e Alcazabas',
    eu: 'Taifa Erresumak – Jauregiak eta Alkazabak',
  },
  'prerromanico-asturiano': {
    es: 'Prerrománico Asturiano – UNESCO',
    ca: 'Prerromànic Asturià – UNESCO',
    en: 'Asturian Pre-Romanesque – UNESCO',
    fr: 'Préroman asturien – UNESCO',
    it: 'Preromanico asturiano – UNESCO',
    pt: 'Pré-Românico Asturiano – UNESCO',
    gl: 'Prerrománico Asturiano – UNESCO',
    eu: 'Asturiar Aurre-erromanikoa – UNESCO',
  },
  'ruta-mozarabe': {
    es: 'Ruta Mozárabe – Toledo y El Bierzo',
    ca: 'Ruta Mossàrab – Toledo i El Bierzo',
    en: 'Mozarabic Route – Toledo and El Bierzo',
    fr: 'Route mozarabe – Tolède et El Bierzo',
    it: 'Itinerario mozarabico – Toledo e El Bierzo',
    pt: 'Rota Moçárabe – Toledo e El Bierzo',
    gl: 'Ruta Mozárabe – Toledo e O Bierzo',
    eu: 'Mozarabiar Ibilbidea – Toledo eta El Bierzo',
  },
  'via-de-la-plata': {
    es: 'Vía de la Plata – Patrimonio Romano',
    ca: 'Via de la Plata – Patrimoni Romà',
    en: 'Vía de la Plata – Roman Heritage',
    fr: 'Vía de la Plata – Patrimoine romain',
    it: 'Vía de la Plata – Patrimonio romano',
    pt: 'Vía de la Plata – Património Romano',
    gl: 'Vía da Prata – Patrimonio Romano',
    eu: 'Zilarraren Bidea – Erromatar Ondarea',
  },
  'megalitica-alentejo': {
    es: 'Ruta Megalítica del Alentejo',
    ca: 'Ruta Megalítica de l\'Alentejo',
    en: 'Megalithic Route of Alentejo',
    fr: 'Route mégalithique de l\'Alentejo',
    it: 'Itinerario megalitico dell\'Alentejo',
    pt: 'Rota Megalítica do Alentejo',
    gl: 'Ruta Megalítica do Alentejo',
    eu: 'Alentejoko Ibilbide Megalitikoa',
  },
  'dolmenes-antequera': {
    es: 'Dólmenes de Antequera – UNESCO',
    ca: 'Dòlmens d\'Antequera – UNESCO',
    en: 'Dolmens of Antequera – UNESCO',
    fr: 'Dolmens d\'Antequera – UNESCO',
    it: 'Dolmen di Antequera – UNESCO',
    pt: 'Dólmens de Antequera – UNESCO',
    gl: 'Dólmenes de Antequera – UNESCO',
    eu: 'Antequerako Trikuharriak – UNESCO',
  },
  'arte-rupestre-cantabrico': {
    es: 'Arte Rupestre Paleolítico – Cornisa Cantábrica',
    ca: 'Art Rupestre Paleolític – Cornisa Cantàbrica',
    en: 'Palaeolithic Rock Art – Cantabrian Coast',
    fr: 'Art rupestre paléolithique – Corniche cantabrique',
    it: 'Arte rupestre paleolitica – Cornice cantabrica',
    pt: 'Arte Rupestre Paleolítica – Cornija Cantábrica',
    gl: 'Arte Rupestre Paleolítica – Cornixa Cantábrica',
    eu: 'Paleolitoko Labar Artea – Kantauriko Itsasertza',
  },
  'fortificaciones-vauban': {
    es: 'Fortificaciones de Vauban – UNESCO',
    ca: 'Fortificacions de Vauban – UNESCO',
    en: 'Fortifications of Vauban – UNESCO',
    fr: 'Fortifications de Vauban – UNESCO',
    it: 'Fortificazioni di Vauban – UNESCO',
    pt: 'Fortificações de Vauban – UNESCO',
    gl: 'Fortificacións de Vauban – UNESCO',
    eu: 'Vaubanen Gotorlekuak – UNESCO',
  },
  'castillos-frontera-cataluna': {
    es: 'Castillos de Frontera – Cataluña',
    ca: 'Castells de Frontera – Catalunya',
    en: 'Frontier Castles – Catalonia',
    fr: 'Châteaux frontaliers – Catalogne',
    it: 'Castelli di frontiera – Catalogna',
    pt: 'Castelos de Fronteira – Catalunha',
    gl: 'Castelos de Fronteira – Cataluña',
    eu: 'Mugako Gazteluak – Katalunia',
  },
  'camino-frances': {
    es: 'Camino Francés – Ruta Jacobea Principal',
    ca: 'Camí Francès – Ruta Jacobea Principal',
    en: 'French Way – Main Jacobean Route',
    fr: 'Camino Francés – Voie jacquaire principale',
    it: 'Camino Francés – Via jacopea principale',
    pt: 'Caminho Francês – Rota Jacobeia Principal',
    gl: 'Camiño Francés – Ruta Xacobea Principal',
    eu: 'Bide Frantsesa – Donejakue Bide Nagusia',
  },
  'camino-primitivo': {
    es: 'Camino Primitivo – La Primera Ruta Jacobea',
    ca: 'Camí Primitiu – La Primera Ruta Jacobea',
    en: 'Primitive Way – The First Jacobean Route',
    fr: 'Camino Primitivo – La première voie jacquaire',
    it: 'Camino Primitivo – La prima via jacopea',
    pt: 'Caminho Primitivo – A Primeira Rota Jacobeia',
    gl: 'Camiño Primitivo – A Primeira Ruta Xacobea',
    eu: 'Bide Primitiboa – Lehen Donejakue Bidea',
  },
  'camino-portugues': {
    es: 'Camino Portugués – Lisboa/Porto a Santiago',
    ca: 'Camí Portuguès – Lisboa/Porto a Santiago',
    en: 'Portuguese Way – Lisbon/Porto to Santiago',
    fr: 'Camino Portugués – Lisbonne/Porto à Saint-Jacques',
    it: 'Camino Portugués – Lisbona/Porto a Santiago',
    pt: 'Caminho Português – Lisboa/Porto a Santiago',
    gl: 'Camiño Portugués – Lisboa/Porto a Santiago',
    eu: 'Bide Portugesa – Lisboa/Porto Santiagora',
  },
  'modernismo-catalan': {
    es: 'Modernismo Catalán – Gaudí y Domènech',
    ca: 'Modernisme Català – Gaudí i Domènech',
    en: 'Catalan Modernism – Gaudí and Domènech',
    fr: 'Modernisme catalan – Gaudí et Domènech',
    it: 'Modernismo catalano – Gaudí e Domènech',
    pt: 'Modernismo Catalão – Gaudí e Domènech',
    gl: 'Modernismo Catalán – Gaudí e Domènech',
    eu: 'Kataluniako Modernismoa – Gaudí eta Domènech',
  },
  'palacios-reales': {
    es: 'Palacios Reales – Sitios Reales de España',
    ca: 'Palaus Reials – Reials Llocs d\'Espanya',
    en: 'Royal Palaces – Royal Sites of Spain',
    fr: 'Palais royaux – Sites royaux d\'Espagne',
    it: 'Palazzi reali – Siti reali di Spagna',
    pt: 'Palácios Reais – Sítios Reais de Espanha',
    gl: 'Pazos Reais – Sitios Reais de España',
    eu: 'Errege Jauregiak – Espainiako Errege Lekuak',
  },
  'ceramica-toledana': {
    es: 'Cerámica Toledana – Patrimonio UNESCO',
    ca: 'Ceràmica de Toledo – Patrimoni UNESCO',
    en: 'Toledo Pottery – UNESCO Heritage',
    fr: 'Céramique de Tolède – Patrimoine UNESCO',
    it: 'Ceramica di Toledo – Patrimonio UNESCO',
    pt: 'Cerâmica de Toledo – Património UNESCO',
    gl: 'Cerámica de Toledo – Patrimonio UNESCO',
    eu: 'Toledoko Zeramika – UNESCO Ondarea',
  },
};

const LOCALES = ['es','ca','en','fr','it','pt','gl','eu'];

for (const lng of LOCALES) {
  const file = path.join(DIR, `${lng}.json`);
  const json = JSON.parse(fs.readFileSync(file, 'utf8'));
  json.curatedRoutes = json.curatedRoutes || {};
  json.curatedRoutes.routes = json.curatedRoutes.routes || {};
  let added = 0;
  for (const [id, names] of Object.entries(ROUTES)) {
    if (!json.curatedRoutes.routes[id]) json.curatedRoutes.routes[id] = {};
    if (json.curatedRoutes.routes[id].name !== names[lng]) {
      json.curatedRoutes.routes[id].name = names[lng];
      added++;
    }
  }
  fs.writeFileSync(file, JSON.stringify(json, null, 2) + '\n', 'utf8');
  console.log(`${lng}.json: ${added} nombres de rutas`);
}
